<?php

/*
Plugin Name: A.I.D. - Admin Issue Diagnostic
Plugin URI: https://github.com/PopVeKind/admin_issue_diagnostic
Description: AID collects environmentals and formats a template to copy/paste into a YOURLS issue. Fantastic for newbies, great for experts!
Version: 1.0
Author: Pop VeKind
Author URI: https://vekind.org/about-vekind/pop-vekind/
TIP: Just fill in the blanks!
*/

/**
 * Must be logged in.
 * 
 * No direct call.
 */

if( !defined( 'YOURLS_ABSPATH' ) ) die();

/**
 * Register the plugin
 */

yourls_add_action( 'plugins_loaded', 'pop_vekind_admin_issue_diagnostic_add_page' );

function pop_vekind_admin_issue_diagnostic_add_page() {
	// parameters: page slug, page title, and function that will display the page itself
	yourls_register_plugin_page( 'admin_issue_diagnostic', 'Admin Issue Diagnostic - A.I.D.', 'pop_vekind_admin_issue_diagnostic_do_page' );
}

/**
 * Admin Issue Diagnostic
 */

function pop_vekind_admin_issue_diagnostic_do_page() {

	/**
	 * Collect Environmentals
	 */

	$yourlsver = yourls_get_option( 'version' );
	$dbver = yourls_get_option( 'db_version' );
	//	$mysqlver should equal function mysql_version() from YDB.php.
	$phpver = phpversion();
	$phpos = PHP_OS;
	$server_software = $_SERVER['SERVER_SOFTWARE'];
	$browser = $_SERVER['HTTP_USER_AGENT'];

	/**
	 * Output Issue Templete
	 * 
	 * Note: This output is formatted with <br /> to allow an HTML output
	 *   That can be copy/pasted into a markdown issue on Github..
	 */

	echo <<<HTML
	<h2>A.I.D. - Admin Issue Diagnostic</h2>
	<p><br />## Technical details regarding my environment
	<br />- YOURLS version: $yourlsver
	<br />- Plugins enabled:
HTML;
	foreach (yourls_get_option( 'active_plugins' ) as $key => $value) {
		echo '<br />&nbsp;&nbsp;&nbsp;&nbsp;1. ' . $value;
	}
	echo <<<HTML
	<br />- YOURLS DB Ver:  $dbver
	<br />- PHP version: $phpver
	<br />- Server OS Build: $phpos
	<br />- Server & version: $server_software
	<br />- Browser information:  $browser
	<br /><br />- Generated by the AID Plugin ver 1.0
	<br /><br />## Bug description
	<br /><br />### What is the current behavior?
	<br />This is a bug because…
	<br /><br />### What is the expected or desired behavior?
	<br /><br />## Reproducible bug summary steps
	<br />1. 
	<br />1. 
	<br />1. 
	</p>
	<p>#####<i> Do NOT copy this line or below. </i>#####</p>
	<p><i>Please copy/paste the above block of information into any support issue you raise. Thank You.</i></p>';
HTML;
}
